version: '3'
services:
    shop-proxy:
        container_name: shop-proxy
        hostname: shop-proxy
        image: nginx
        restart: unless-stopped
        volumes:
            - ./nginx:/etc/nginx
            - /home/project/ssl:/etc/ssl
        ports:
            - 443:443
            - 127.0.0.1:3000:3000
            - 127.0.0.1:5173:5173
        networks:
            - shop_backend
            - shop_frontend
            - monitoring
networks:
    shop_backend:
        name: shop_backend
    shop_frontend:
        name: shop_frontend
    monitoring:
        name: monitoring
